version: "3"

services:
    php80:
        image: anax/dev:php80-cli
        volumes:
            - .:/home/anax/repo

    php80-apache:
        image: anax/dev:php80-apache
        ports:
            - "18080:80"
        volumes:
            - .:/app
            - ./apache.conf:/etc/apache2/sites-enabled/000-default.conf
